#!/usr/bin/env python3
# ========================================================================
# SPDX-FileCopyrightText: 2026 Simon Dorrer and Harald Pretl
# Johannes Kepler University, Institute for Integrated Circuits
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# SPDX-License-Identifier: Apache-2.0
#
# This script reorders the .subckt pin list of a SPICE or XSPICE netlist
# to match the pin order of an Xschem .sym symbol file, so the netlist
# can be instantiated by that symbol in an Xschem testbench.
# ========================================================================

"""Reorder .subckt pins of a (X)SPICE netlist to match an Xschem symbol.

Xschem netlists a symbol instance as ``@name @pinlist @symname``, so the
``.subckt`` port order of the referenced netlist must match the order of
the ``B 5`` pin lines in the ``.sym`` file. Netlist generators, however,
emit their own port order (Magic, for instance, sorts ports
alphabetically). This tool rewrites the ``.subckt`` header accordingly.

Two netlist formats are handled (auto-detected, see ``--format``):

  - **spice**: an analog netlist, e.g. from parasitic extraction (PEX)
    with Magic or KLayout/kpex. Pin names in the netlist and the symbol
    are expected to be identical (or declared via ``sim_pinname``, see
    below); pins are matched by name. A flattened 1-bit bus is
    reconciled first: if the symbol declares ``X[0]`` but the netlist
    has the scalar ``X`` (a common Yosys/LibreLane side-effect for
    width-1 Verilog buses), the scalar is renamed to ``X[0]``
    throughout the whole file so internal references stay consistent.
  - **xspice**: a digital XSPICE model generated by ``spi2xspice.py``,
    whose ports are the original netlist names prefixed with ``a_`` and
    with bus brackets flattened (``counter_value_o[0]`` ->
    ``a_counter_value_o_0_``).

Pin matching:

  - **Name mode (preferred, order-independent):** if *every* symbol pin
    carries a ``sim_pinname=<netlist_name>`` property, that property is
    the pin's real name in the source netlist and pins are matched by
    name. For xspice netlists the ``a_``-prefixed/flattened form is
    derived automatically. This mode is immune to the netlister's port
    order. In spice format, pins without ``sim_pinname`` simply match by
    their symbol name, so identical names need no extra properties.
  - **Positional mode (xspice fallback):** if not all pins carry
    ``sim_pinname``, power pins are matched by a fixed name map
    (``VDD`` <-> ``a_VPWR``, ``VSS`` <-> ``a_VGND``) and every other pin
    by position: the i-th non-power symbol pin maps to the i-th
    non-power ``.subckt`` pin. Only correct when the netlist keeps the
    symbol's port order.

Pin ordering from the symbol supports two modes:

  - ``sim_pinnumber`` mode: if *every* ``B 5`` pin line (or bus group)
    carries a ``sim_pinnumber=<n>`` property, the entries are sorted by
    that number. Useful when the geometric order of pins in the .sym
    file does not reflect the intended electrical pin order (e.g. the
    IHP bipolar symbols).
  - Appearance-order mode (default): otherwise the order of appearance
    in the .sym file is used.

Bus pins in the symbol use the Xschem range syntax ``name[A..B]`` and
are expanded into individual indexed pins (``name[A]``, ``name[A+1]``,
..., ``name[B]``) before matching. A bus ``sim_pinname`` may be given as
a bare base (``counter_value_o``) or with a range; the symbol bus
indices are applied to it.

Usage:
    sak-pin-reorder.py <sym_file> <netlist_file> [-o <output_file>]
                       [--format auto|spice|xspice]

If -o is not given, the netlist file is overwritten in-place.
"""

import argparse
import re
import sys


# Positional xspice fallback: power pins are matched by this fixed name map.
POWER_MAP = {'VDD': 'a_VPWR', 'VSS': 'a_VGND'}
XSPICE_POWER = set(POWER_MAP.values())

# An XSPICE netlist from spi2xspice.py contains digital event-driven models.
XSPICE_MODEL_PATTERN = re.compile(
    r'^\s*\.model\s+\S+\s+(?:d_lut|d_genlut|d_dff|d_dlatch|d_pullup|'
    r'd_pulldown|adc_bridge|dac_bridge)\b',
    re.IGNORECASE)


def parse_sym_pins(sym_path: str) -> list[tuple[str, str | None]]:
    """Extract pins from a .sym file as ``(display_name, real_name)`` pairs.

    Pins are defined as:
    ``B 5 ... {name=<pin_name> dir=<dir> [sim_pinnumber=<n>] [sim_pinname=<net>]}``

    ``real_name`` is the netlist-side name declared by ``sim_pinname=`` (or
    ``None`` when the pin has no such property). Bus pins are expanded and
    ``sim_pinnumber`` sorting is applied as described in the module docstring.
    """
    pin_pattern = re.compile(r'^B\s+5\s+.*\{name=(\S+)\s+dir=\w+[^}]*\}')
    bus_range_pattern = re.compile(r'^(.+)\[(\d+)\.\.(\d+)\]$')
    sim_num_pattern = re.compile(r'sim_pinnumber=(\d+)')
    sim_name_pattern = re.compile(r'sim_pinname=([^\s}]+)')
    raw = []  # list of (sim_pinnumber | None, [(display, real|None), ...])
    with open(sym_path, 'r') as f:
        for line in f:
            stripped = line.strip()
            m = pin_pattern.match(stripped)
            if not m:
                continue
            name = m.group(1)
            sn = sim_num_pattern.search(stripped)
            sim_num = int(sn.group(1)) if sn else None
            pn = sim_name_pattern.search(stripped)
            real = pn.group(1) if pn else None
            bm = bus_range_pattern.match(name)
            if bm:
                base = bm.group(1)
                a, b = int(bm.group(2)), int(bm.group(3))
                step = 1 if a <= b else -1
                idxs = list(range(a, b + step, step))
                if real is not None:
                    rbm = bus_range_pattern.match(real)
                    rbase = rbm.group(1) if rbm else real
                    expanded = [(f'{base}[{i}]', f'{rbase}[{i}]') for i in idxs]
                else:
                    expanded = [(f'{base}[{i}]', None) for i in idxs]
            else:
                expanded = [(name, real)]
            raw.append((sim_num, expanded))
    if raw and all(n is not None for n, _ in raw):
        raw.sort(key=lambda x: x[0])
    pins = []
    for _, expanded in raw:
        pins.extend(expanded)
    return pins


def parse_subckt_from_lines(
    lines: list[str],
) -> tuple[str, list[str], int, int, str]:
    """Extract the subcircuit name and pin list from the first .subckt in lines.

    SPICE cards are case-insensitive and netlisters disagree: xschem and
    Magic write ``.subckt``, KLayout-PEX writes ``.SUBCKT``. The card is
    therefore matched case-insensitively and its original spelling is
    returned so the rewritten header keeps the file's own style.

    Handles continuation lines starting with '+'.
    Returns (subckt_name, pin_list, first_line_index, last_line_index, keyword).
    """
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped[:7].lower() == '.subckt':
            parts = stripped.split()
            keyword = parts[0]
            subckt_name = parts[1]
            pins = parts[2:]
            last = i
            for j in range(i + 1, len(lines)):
                cont = lines[j].strip()
                if cont.startswith('+'):
                    pins.extend(cont[1:].split())
                    last = j
                else:
                    break
            return subckt_name, pins, i, last, keyword
    raise ValueError("No .subckt line found in the netlist file")


def detect_format(lines: list[str], netlist_pins: list[str]) -> str:
    """Auto-detect 'xspice' vs 'spice' from the netlist content.

    A netlist is treated as XSPICE when it contains digital event-driven
    .model definitions (spi2xspice.py always writes them), or - in case
    the models were moved to an external include file - when every
    .subckt port carries the characteristic ``a_`` prefix.
    """
    if any(XSPICE_MODEL_PATTERN.match(ln) for ln in lines):
        return 'xspice'
    if netlist_pins and all(p.startswith('a_') for p in netlist_pins):
        return 'xspice'
    return 'spice'


def sim_pinname_to_xspice(real: str) -> str:
    """Derive the XSPICE .subckt pin name from a netlist name.

    Mirrors ``spi2xspice.py``: prefix ``a_`` and flatten bus brackets,
    so ``clock_i`` -> ``a_clock_i`` and ``counter_value_o[0]`` ->
    ``a_counter_value_o_0_``.
    """
    return 'a_' + real.replace('[', '_').replace(']', '_')


def build_mapping_xspice(sym_pins: list[tuple[str, str | None]],
                         xspice_pins: list[str]) -> list[tuple[str, str]]:
    """Pair each sym pin with an XSPICE pin.

    If every sym pin declares a real name (``sim_pinname``), pins are
    matched by name (order-independent). Otherwise the positional scheme
    is used: VDD/VSS by the power name-map, all others by position.
    Returns a list of ``(display_name, xspice_pin)`` pairs in sym order.
    """
    # Name mode: every symbol pin carries a sim_pinname property.
    if all(real is not None for _, real in sym_pins):
        xspice_set = set(xspice_pins)
        mapping = []
        for display, real in sym_pins:
            xp = sim_pinname_to_xspice(real)
            if xp not in xspice_set:
                raise ValueError(
                    f"Symbol pin '{display}' (sim_pinname={real}) expects "
                    f"XSPICE pin '{xp}', which is not in the .subckt. "
                    f"XSPICE pins: {sorted(xspice_pins)}"
                )
            mapping.append((display, xp))
        mapped = [xp for _, xp in mapping]
        if len(set(mapped)) != len(mapped):
            dupes = sorted({xp for xp in mapped if mapped.count(xp) > 1})
            raise ValueError(
                f"sim_pinname mapping is not one-to-one; "
                f"multiple symbol pins map to: {dupes}"
            )
        return mapping

    # Positional fallback (some pins lack sim_pinname).
    display_names = [d for d, _ in sym_pins]
    sym_power = {p for p in display_names if p in POWER_MAP}
    xspice_power = {p for p in xspice_pins if p in XSPICE_POWER}
    expected_xspice_power = {POWER_MAP[p] for p in sym_power}
    if expected_xspice_power != xspice_power:
        raise ValueError(
            f"Power pin mismatch: sym {sorted(sym_power)} maps to "
            f"{sorted(expected_xspice_power)}, but xspice has "
            f"{sorted(xspice_power)}. Hint: declare sim_pinname= on every "
            f"symbol pin to match pins by name instead."
        )

    signal_xspice = [p for p in xspice_pins if p not in XSPICE_POWER]
    sig_iter = iter(signal_xspice)

    mapping = []
    for display in display_names:
        if display in POWER_MAP:
            mapping.append((display, POWER_MAP[display]))
        else:
            mapping.append((display, next(sig_iter)))
    return mapping


def reconcile_scalar_buses(
    lines: list[str],
    target_names: list[str],
    netlist_pins: list[str],
) -> tuple[list[str], list[str], list[tuple[str, str]]]:
    """Rename flattened scalar pins (``X``) to bus-of-one form (``X[0]``).

    Yosys/LibreLane flatten 1-bit Verilog buses, so a port declared
    ``[0:0] input_PAD`` in RTL becomes the scalar ``input_PAD`` in the
    extracted SPICE, while the schematic-side symbol still uses
    ``input_PAD[0]``.  This pass detects such pairs and rewrites the
    scalar to the bus-of-one form throughout the whole SPICE file so
    the subsequent pin-set check and reorder succeed and internal
    element/connection references stay consistent.

    Returns (rewritten_lines, updated_netlist_pins, [(scalar, bus0), ...]).
    If no renames are needed, the inputs are returned unchanged.
    """
    netlist_set = set(netlist_pins)
    bus0_pattern = re.compile(r'^(.+)\[0\]$')
    rename: dict[str, str] = {}
    for s in target_names:
        m = bus0_pattern.match(s)
        if m:
            scalar = m.group(1)
            if scalar in netlist_set and s not in netlist_set:
                rename[scalar] = s
    if not rename:
        return lines, netlist_pins, []

    # Token-boundary regex: require non-word and non-'[' on both sides so that
    # 'input_PAD[0]' (already bus-of-one) and identifiers like 'input_PAD2CORE'
    # are left untouched.
    alternation = '|'.join(re.escape(k) for k in rename)
    token_pattern = re.compile(
        r'(?<![\w\[])(' + alternation + r')(?![\w\[])'
    )
    new_lines = [
        token_pattern.sub(lambda m: rename[m.group(1)], ln)
        for ln in lines
    ]
    _, new_netlist_pins, _, _, _ = parse_subckt_from_lines(new_lines)
    return new_lines, new_netlist_pins, sorted(rename.items())


def build_mapping_spice(sym_pins: list[tuple[str, str | None]],
                        netlist_pins: list[str]) -> list[tuple[str, str]]:
    """Pair each sym pin with a SPICE pin by name.

    The netlist-side name of a pin is its ``sim_pinname`` when declared,
    or its symbol name otherwise (names identical in symbol and netlist).
    Returns a list of ``(display_name, netlist_pin)`` pairs in sym order.
    """
    targets = [real if real is not None else display
               for display, real in sym_pins]
    if set(targets) != set(netlist_pins):
        missing_in_sym = set(netlist_pins) - set(targets)
        missing_in_netlist = set(targets) - set(netlist_pins)
        msg = "Pin set mismatch!\n"
        if missing_in_sym:
            msg += f"  Netlist pins not in symbol: {missing_in_sym}\n"
        if missing_in_netlist:
            msg += f"  Symbol pins not in netlist: {missing_in_netlist}\n"
        raise ValueError(msg)
    if len(set(targets)) != len(targets):
        dupes = sorted({t for t in targets if targets.count(t) > 1})
        raise ValueError(f"Symbol maps multiple pins to: {dupes}")
    return [(display, target)
            for (display, _), target in zip(sym_pins, targets)]


def rewrite_subckt_header(
    lines: list[str],
    subckt_name: str,
    ordered_pins: list[str],
    first_idx: int,
    last_idx: int,
    keyword: str = '.subckt',
) -> list[str]:
    """Return a copy of ``lines`` with the .subckt header replaced by one
    listing ``ordered_pins``, wrapped to ~80 columns with '+' continuations.

    ``keyword`` is the card as spelled in the source file, so a netlist
    written with ``.SUBCKT`` keeps its case."""
    max_width = 80
    header = f"{keyword} {subckt_name}"
    subckt_lines = []
    current = header
    for pin in ordered_pins:
        if len(current) + 1 + len(pin) > max_width:
            subckt_lines.append(current + "\n")
            current = "+ " + pin
        else:
            current += " " + pin
    subckt_lines.append(current + "\n")
    return lines[:first_idx] + subckt_lines + lines[last_idx + 1:]


def main():
    parser = argparse.ArgumentParser(
        description="Reorder (X)SPICE .subckt pins to match Xschem .sym pin order."
    )
    parser.add_argument("sym_file", help="Path to the Xschem .sym file")
    parser.add_argument("netlist_file", help="Path to the .spice/.xspice file")
    parser.add_argument("-o", "--output", default=None,
                        help="Output file path (default: overwrite netlist in-place)")
    parser.add_argument("--format", choices=["auto", "spice", "xspice"],
                        default="auto",
                        help="Netlist format (default: auto-detect)")
    args = parser.parse_args()

    output_path = args.output if args.output else args.netlist_file

    # 1. Parse pin lists (sym pins come back with bus ranges already expanded)
    sym_pins = parse_sym_pins(args.sym_file)
    with open(args.netlist_file, 'r') as f:
        lines = f.readlines()
    subckt_name, netlist_pins, _, _, _ = parse_subckt_from_lines(lines)

    fmt = args.format
    if fmt == "auto":
        fmt = detect_format(lines, netlist_pins)

    all_named = bool(sym_pins) and all(r is not None for _, r in sym_pins)
    if fmt == "xspice":
        mode = "name (sim_pinname)" if all_named else "positional"
    else:
        mode = "name (sim_pinname)" if all_named else "name (identical)"

    print(f"Symbol file:  {args.sym_file}")
    print(f"Netlist file: {args.netlist_file}")
    print(f"Subcircuit:   {subckt_name}")
    print(f"Format:       {fmt}" + (" (auto-detected)" if args.format == "auto" else ""))
    print(f"Match mode:   {mode}")
    print(f"Sym pins:     {len(sym_pins)}")
    print(f"Netlist pins: {len(netlist_pins)}")

    if len(sym_pins) != len(netlist_pins):
        raise ValueError(
            f"Pin count mismatch: sym has {len(sym_pins)}, "
            f"netlist has {len(netlist_pins)} (after bus expansion)"
        )

    # 2. Pair sym pins with netlist pins
    if fmt == "xspice":
        mapping = build_mapping_xspice(sym_pins, netlist_pins)
    else:
        # Reconcile flattened 1-bit buses (scalar 'X' -> bus 'X[0]') across
        # the whole SPICE file, not just the .subckt header.
        targets = [r if r is not None else d for d, r in sym_pins]
        lines, netlist_pins, renames = reconcile_scalar_buses(
            lines, targets, netlist_pins)
        if renames:
            print("\nRenamed flattened scalar pins to match symbol bus notation:")
            for scalar, bus0 in renames:
                print(f"  {scalar} -> {bus0}")
        mapping = build_mapping_spice(sym_pins, netlist_pins)

    ordered_netlist = [np for _, np in mapping]

    # 3. Show mapping
    print("\nPin mapping (sym -> netlist):")
    for sp, np in mapping:
        old_idx = netlist_pins.index(np)
        new_idx = ordered_netlist.index(np)
        marker = "" if new_idx == old_idx else " *REORDERED*"
        print(f"  {sp:25s} -> {np:25s}{marker}")

    # 4. Reorder subckt header and write back
    _, _, first_idx, last_idx, keyword = parse_subckt_from_lines(lines)
    lines = rewrite_subckt_header(lines, subckt_name, ordered_netlist,
                                  first_idx, last_idx, keyword)
    with open(output_path, 'w') as f:
        f.writelines(lines)

    print(f"\nReordered netlist written to: {output_path}")


if __name__ == "__main__":
    try:
        main()
    except ValueError as e:
        print(f"[ERROR] {e}", file=sys.stderr)
        sys.exit(1)
