// Auto-generated by LibreLane
module heichips26_digital_project(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input[7:0] ui_in,
  output[7:0] uo_out,
  input[7:0] uio_in,
  output[7:0] uio_out,
  output[7:0] uio_oe,
  input ena,
  input clk,
  input rst_n
);
endmodule
