# SPDX-FileCopyrightText: 2026 The HeiChips Contributors
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1

meta:
  version: 3
  flow: Classic
  substituting_steps:

    # Magic reports some overlaps which can be ignored
    Checker.IllegalOverlap: null

DESIGN_NAME: counter
VERILOG_FILES: dir::../../rtl/*.sv

# Clock
CLOCK_PORT: clk_i
CLOCK_NET: clk_i
CLOCK_PERIOD: 20 # in ns == 50 MHz

# Layout / Floorplan Rules
FP_SIZING: absolute
DIE_AREA: [0, 0, 80, 80]
PL_TARGET_DENSITY_PCT: 40
GRT_ALLOW_CONGESTION: true

# Set the margin
TOP_MARGIN_MULT: 1
BOTTOM_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 8
RIGHT_MARGIN_MULT: 8

# Valid values are AREA 0-3 and DELAY 0-4
# DELAY 4 = fastest, but largest area
# AREA 3 = slowest, but smallest area
SYNTH_STRATEGY: DELAY 4

# Use Metal2/Metal3 straps
PDN_VERTICAL_LAYER: Metal2
PDN_HORIZONTAL_LAYER: Metal3
RT_MAX_LAYER: Metal4

# Pin placement
FP_PIN_ORDER_CFG: dir::pin_order.cfg

# SDC files
PNR_SDC_FILE: dir::impl.sdc
SIGNOFF_SDC_FILE: dir::signoff.sdc

# Enable plugin for better SystemVerilog support
# USE_SLANG: True
